### PR TITLE
Lace tool support and explicit memo in raw files

### PR DESCRIPTION
**Pull request by mangelajo**
ASCII lace tool definition and compilator to raw image, plus support for
explicit memos in the raw files.

Refactor of a few image manipulation functions to hold the image in a structure
along with the memo data.

This is untested for the KH-930 version, but the code parts where so similar
that I'm confident it may work well.

Usage example:

```
python lace/lace_compiler.py lace/examples/fox.lace out.raw && \
           ./bin-linux/cli a out.raw e /dev/ttyUSB0 q
```

### CODE REVIEW

**Comment by mangelajo** [comment]
By the way, awesome work!!!, your C code is much better than all the python code there's around ;)

If you don't have time to go on with the project I could take care of it for a while, I guess I'm going to be making use of it for some time, regarding this, did you have any licensing model in mind? GPL/MIT/BSD/Apache? :)

**Comment by stg** [comment]
Thanks for getting in touch, showing interest and the compliment :)

I've added you as a collaborator and feel free to update the README to reflect this.

I haven't worked on this in a long time and I honestly just want it out there for anyone to do with as they please. Not educated on licensing, so if you want - feel free to choose a suitable license to pair with the project.

The only goal I ever had for the project was to keep it simple enough to be used by most anyone, as many people get scared off by even the simplest of command line interfacing. Project was started because existing solutions at the time would not handle the machine that an artist acquaintance had brought to my workshop.

Still happens that machines are unable to decode the produced image. I believe this is due to the need for an extra zero byte between patterns sometimes but I was never able to figure out when this is needed as I could not find any pattern to it's occurrences when going through images produced by the machine itself.

**Comment by mangelajo** [comment]
Thanks! :-) I will update the README.

I guess GPL or Apache could be good licenses (MIT and BSD means anyone can make a closed source fork.. if I'm not wrong, and Apache is similar to GPL, but your force contributing companies to give up patent permissions on contributed code.)

I need to check if the GUI part still fits in the new LIB image bits. I will check that before merging.

Do you have any example of the images that were not properly decoded? I could try to look at that.

Best,
Miguel

**Comment by stg** [comment]
Sounds good :)

No examples, no. It's user reports nothing else. But it supposedly only happens when there is multiple patterns in a single disk image, which is why I suspect the mentioned byte.

The only documentation reference I made to this is line 100 in the kh940_format.txt file.

This document is not entirely up to date - there were a few later realizations.
Also made a mistake when interpreting the file - it is stored backwards (last byte first).
Didn't realize until the code was done but it would have been more straight forward, had I seen this first. The 930 stores data in natural order, which keyed me in to the fact as they are very similar apart from the 940 reversal.

**Comment by mangelajo** [comment]
Wow, I didn't see the video-game style interface until now. Amazing :-) :+1: 

I need to think about adding GUI support for the lace tool thing.

Cheers,
Miguel Ángel.

**Comment by stg** [comment]
Haha, thanks though "amazing" is not what I'd choose.
"Weird" or "dodgy" would be closer to heart :D
It was my first attempt at a UI library.
Seems to do the job though :)

**Pull request merged**
